site_name: My Awesome Mod Site

nav:
    - Home: index.md
    - About: about.md

theme:
  name: material

repo_url: https://github.com/pairofdocs/site-mkdoc

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
